server:
  port: ${PORT:8080}   # Render sẽ đặt PORT động, local mặc định 8080

spring:
  application:
    name: hrms-backend
  datasource:
    url: jdbc:mysql://root:wvqHOdOYsbkdLVNcMRvtDwIavSwFPZjQ@mysql.railway.internal:3306/railway
    username: hrms
    password: wvqHOdOYsbkdLVNcMRvtDwIavSwFPZjQ
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    sep490.com.example.hrms_backend: DEBUG

management:
  endpoints:
    web.exposure.include: health,info
